apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-lke-monitor-kube-prometheu-prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/instance: lke-monitor-kube-prometheu-prometheus
  serviceName: "prometheus-lke-monitor-kube-prometheu-prometheus"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/instance: lke-monitor-kube-prometheu-prometheus
    spec:
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.53.1
        args:
          - --web.console.templates=/etc/prometheus/consoles
          - --web.console.libraries=/etc/prometheus/console_libraries
          - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
          - --web.enable-lifecycle
          - --web.external-url=https://prometheus.trebinje.online/prometheus
          - --web.route-prefix=/prometheus
          - --storage.tsdb.retention.time=30d
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.wal-compression
          - --web.config.file=/etc/prometheus/web_config/web-config.yaml
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        ports:
        - containerPort: 9090
          name: web
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/config_out
        - name: prometheus-storage
          mountPath: /prometheus
      volumes:
      - name: prometheus-config
        emptyDir: {} # Define the prometheus-config volume here
  volumeClaimTemplates:
  - metadata:
      name: prometheus-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi

